sudo: false
dist: trusty
language: node_js
node_js:
  - '8'
  - '9'
  - '10'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
  - npm run codecov
notifications:
  email: false
services:
  - redis
